title: Design System
description: A protoype design system
theme: just-the-docs

url: https://simplybenuk.github.io/ui-foundations-prototype/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
